### ISSUE TITLE
Deploying to Heroku fails

### ISSUE THREAD

**Issue by benlangfeld** [statusify/statusify#36]
```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.3
-----> Installing dependencies using bundler 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       You have deleted from the Gemfile:
       * rb-fsevent
       Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have deleted from the Gemfile:
       * rb-fsevent
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app
```

Maybe https://github.com/statusify/statusify/pull/35 would fix this.

**Comment by ur0** [comment]
Yep. Thanks for alerting. I'm merging #35.

**Comment by benlangfeld** [comment]
Do you have an ETA on #35 being merged, @ur0?

**Comment by benlangfeld** [comment]
Unfortunately #35 doesn't completely fix this:

``
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       [SKYLIGHT] [0.10.0] Skylight agent enabled
       rake aborted!
       NameError: uninitialized constant Regressor
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/config/initializers/regressor.rb:3:in `<top (required)>'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/config/environment.rb:5:in `<top (required)>'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/skylight-0.10.0/lib/skylight/probes.rb:81:in `require'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/skylight-0.10.0/lib/skylight/probes.rb:81:in `require'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_a6598f3cd580f097664ddb7a276d001a/statusify-statusify-6667d37/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app
```

**Comment by ur0** [comment]
Woah. We removed regressor, but left the initializer still sticking there. This probably seems the cause of this issue.
